blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/jeremy-boschen/react-adjustable-panels/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/jeremy-boschen/react-adjustable-panels/security/advisories/new
    about: Report a security vulnerability privately
